version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-python-install:
          version: "3.9"
          requires:
            - build
      - test-python-install:
          version: "3.10"
          requires:
            - build
      - test-python-install:
          version: "3.11"
          requires:
            - build
      - test-python-install:
          version: "3.12"
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install uv
          command: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: Build package
          command: |
            source $HOME/.local/bin/env
            uv build

  test-python-install:
    parameters:
      version:
        type: string
        default: "3.11"
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Install uv
          command: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: Smoke Test Install
          command: |
            source $HOME/.local/bin/env
            python3 --version
            uv pip install --system .
            gdrepl --help

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Fetch tags for versioning
          command: git fetch --tags
      - run:
          name: Install uv
          command: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: Build package
          command: |
            source $HOME/.local/bin/env
            uv build
      - run:
          name: Upload to PyPI
          command: |
            source $HOME/.local/bin/env
            uv pip install --system twine
            twine upload dist/* -u __token__ -p $PYPI_TOKEN
